version: '3.7'

services:
    node:
        build: docker/node
        container_name: node
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - 8080:8080
        networks:
            - chat-network

networks:
    chat-network:
        name: chat-network
        external: true